### PR TITLE
Change theme for easier navigation

### PR DESCRIPTION
**Pull request by Thrilleratplay**
Demo of changes can be viewed here: https://thrilleratplay.github.io/heads-wiki/

This is an attempt to create smaller incremental changes I mentioned in a comment in #25 .

### CODE REVIEW

**Comment by tlaurion** [comment]
I love it. @osresearch ?

**Comment by tlaurion** [comment]
Love the ordering. All links on generated pages points correctly to rendered .md pages.

**Comment by Thrilleratplay** [comment]
@tlaurion @osresearch  I should have mentioned that.  This also contains fixes mentioned in #38.

The ordering is the same as that on the index page.  This is mainly to be a functional change (add site navigation and search).  If this is approved, I will continue with breaking down certain pages into subsections, group other pages.  Obviously, changes like that will require more scrutiny but does not make much sense with the current theme's navigation.

**Comment by MrChromebox** [comment]
LGTM

**Comment by SebastianMcMillan** [comment]
Looks wonderful and very readable. +1 from me.

**Pull request merged**
